In [11]:
import pandas as pd
import streamlit as st
# import matplotlib.pyplot as plt

# open file
comsumption_data = pd.read_csv(
    "./My_Electricity_Consumption.csv", delimiter=';')

new_price_data = pd.read_csv(
    "./My_sahkon-hinta-010121-231024.csv", delimiter=';')
# display(comsumption_data.head())
# display(new_price_data.head())


# check datatype
# print('comsumption_data',type(comsumption_data['Time'][3]))
# print('new_price_data',type(new_price_data['Time'][3]))

# Change time format of both files to Pandas datetime
comsumption_data['Time'] = pd.to_datetime(
    comsumption_data['Time'], format='%d.%m.%Y %H:%M', errors='coerce')
new_price_data['Time'] = pd.to_datetime(
    new_price_data['Time'], format='%d/%m/%Y %H.%M')

display(comsumption_data.head())
display(new_price_data.head())

# Rename the columns for easier access and clean-up
# comsumption_data.columns = [
#     'Time', 'Energy (kWh)', 'Status', 'Temperature']

                 Time Energy(kWh)   Status Temperature
0 2023-09-29 00:00:00        0,52  Metered         9,4
1 2023-09-29 01:00:00        0,44  Metered         9,6
2 2023-09-29 02:00:00        0,45  Metered         9,6
3 2023-09-29 03:00:00        0,45  Metered           9
4 2023-09-29 04:00:00        0,44  Metered         9,2

                 Time Price (cent/kWh)
0 2023-09-29 00:59:00            -0,06
1 2023-09-29 01:59:00            -0,06
2 2023-09-29 02:59:00           -0,057
3 2023-09-29 03:59:00           -0,036
4 2023-09-29 04:59:00                0

In [18]:
# Replace commas with dots and convert to numeric for energy consumption
# comsumption_data['Energy (kWh)'] = comsumption_data['Energy (kWh)'].str.replace(
#     ',', '.').astype(float)

print('Show')
display(comsumption_data['Energy (kWh)'])

comsumption_data['Energy (kWh)'] = comsumption_data['Energy (kWh)'].str.replace(
    ',', '.').astype(float)
# new_price_data['Price(cent/kWh)'] = new_price_data['Price(cent/kWh)'].str.replace(
#     ',', '.').astype(float)

# comsumption_data['Temperature'] = comsumption_data['Temperature'].str.replace(
#     ',', '.').astype(float)


# print('Show')
# display(comsumption_data['Energy (kWh)'])

# Merge the datasets on the 'Time' column
data_merge = pd.merge(comsumption_data, new_price_data, on='Time', how='outer')

# print('data_merge')
# display(data_merge)

Show

0       0.52
1       0.44
2       0.45
3       0.45
4       0.44
        ...
9355    0.37
9356    0.36
9357    0.53
9358    0.38
9359    0.97
Name: Energy (kWh), Length: 9360, dtype: float64

AttributeError: Can only use .str accessor with string values!